### ISSUE TITLE
Unable to use local model

### ISSUE THREAD

**Issue by garandal245** [carefree0910/carefree-creator#18]
whenever attempting to use any local models i get a crash with the error below

`2022-11-29 08:55:51,858 - 6812 - root - ERROR - 'cond_stage_model.transformer.text_model.embeddings.token_embedding.weight'
Traceback (most recent call last):
  File "C:\Users\Garry\carefree-creator\.\apis\interface.py", line 247, in switch_checkpoint
    cflearn.scripts.sd.convert(model_path, api, load=True)
  File "C:\Users\Garry\anaconda3\envs\stablediffusion\lib\site-packages\cflearn\scripts\sd.py", line 260, in convert
    nd = _convert_with_key_mapping(inp, md)
  File "C:\Users\Garry\anaconda3\envs\stablediffusion\lib\site-packages\cflearn\scripts\sd.py", line 231, in _convert_with_key_mapping
    nd = _convert_cond_stage(d, md)
  File "C:\Users\Garry\anaconda3\envs\stablediffusion\lib\site-packages\cflearn\scripts\sd.py", line 23, in _convert_cond_stage
    "core.condition_model.m.token_embedding.weight": d[
KeyError: 'cond_stage_model.transformer.text_model.embeddings.token_embedding.weight'`

**Comment by garandal245** [comment]
im stupid nevermind
